---
title: Toolik Chemical Readings Data Review
output: html_output
---

```{r, setup, include=FALSE}
library(tidyverse)
library(janitor)
library(here)
library(stringr)
```

```{r, echo=FALSE}
# Read in data from CSV file
toolik_biochem <- read_csv(here::here("activities", "data", "2011_Kling_Akchem.csv"), na = c(".", "NA"))

# Clean names
toolik_biochem <- janitor::clean_names(toolik_biochem, case = "snake")
toolik_biochem

# Create subset of data
toolik_inlet_biochem <- dplyr::filter(toolik_biochem, site == "Toolik Inlet")
# Only show pH, DOC, and Total dissolved nitrogen
toolik_inlet_biochem <- toolik_inlet_biochem |>
  select(p_h, doc_u_m, tdn_u_m)

toolik_inlet_biochem

# Calculate the mean of each column with a different method for each
for (i in 1:ncol(toolik_inlet_biochem)) {
  print(toolik_inlet_biochem[, i])
  mean_value <- mean(toolik_inlet_biochem[[i]], na.rm = TRUE)
  # Round mean value to 2 places
  mean_value <- format(round(mean_value, 2), nsmall = 2)
  column_name <- colnames(toolik_inlet_biochem)[i]
  print(paste0("The average value for ", column_name, " in the Toolik Inlet is ", mean_value))
}
# Using across
?apply()
# Using apply to calculate the mean
column_means_apply <- apply(X = toolik_inlet_biochem, MARGIN = 2, FUN = mean, na.rm = TRUE)
print(column_means_apply)

# Use Purrr:Map_df to calculate the mean
?map_df()
col_mean_values_map <- map_df(.x = toolik_inlet_biochem, .f = mean, .id = NULL, na.rm = TRUE)
col_mean_values_map

```
